### ISSUE TITLE
Error while running MVC Sample Example

### ISSUE THREAD

**Issue by parth7676** [auth0/auth0-aspnet-owin#23] opened 2016-01-07 05:32 UTC
![image](https://cloud.githubusercontent.com/assets/14904762/12162895/ea2ab85e-b52d-11e5-91dc-ad2719470686.png)

Why  i am getting this Exception???
What may be the problem??

**Comment by hardvin** [comment] 2016-03-07 17:54
I Have the same Error.

**Comment by JasonSilvestri** [comment] 2016-04-28 04:49
Are you guys installing the Nugget packages? Also, setting up the callback Urls in the Auth0 Application Settings needs to be done. You won't get a id token match return. After the user has authenticated using Auth0, an HTTP POST back to the /signin-auth0 path of your website is done, which will be intercepted by the Auth0 OWIN middleware. For security purposes, they have us register the URL on the Application Settings section of your Auth0 Dashboard. In other words, plan to sign up and pay for the license. Totally worth it, though.

**Comment by jerriep** [comment] 2016-04-28 06:39
I cannot reproduce. @parth7676 and @hardvin can either of you please describe to me the exact steps you are following to reproduce?

**Comment by JasonSilvestri** [comment] 2016-04-28 19:51
@jerriep It cannot be reproduced, because your environment is configured correctly. I think it is on the Auth0 end of their configuration.

**Comment by hardvin** [comment] 2016-04-28 20:47
I Solved!

Thank You

**Comment by JasonSilvestri** [comment] 2016-04-28 21:07
Cool beans! For the sake of clarity, would you mind briefly describing to the collective group what was done to solve the issue in case others have the same issue?

**Comment by hardvin** [comment] 2016-04-28 21:23
At this link is my step to step to solve the problem.

https://www.dropbox.com/s/em1pp9m95bj4ors/Solve%20problem.docx?dl=0

**Comment by jerriep** [comment] 2016-04-29 00:40
Glad you got it solved @hardvin 

I am going to close this issue. But if any of you still have an issue, please open a support ticket of the Auth0 Support Centre (https://auth0.com/support), and let me know here what the ticket# is so I can pick it up.

Also if you open a ticket please try and attach a sample app which demonstrates you problem as it can become very difficult otherwise to track down the issue.

**Closed by jerriep** 2016-04-29 00:40 UTC
